apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamster
  namespace: default
  labels:
    app.kubernetes.io/instance: myapp
spec:
  selector:
    matchLabels:
      app: hamster
  replicas: 2
  template:
    metadata:
      labels:
        app: hamster
    spec:
      containers:
        - name: hamster
          image: ubuntu
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          command: ["/bin/sh"]
          args:
            - "-c"
            - "while true; do env; sleep 10; done"
        - name: hamster2
          image: ubuntu
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          command: ["/bin/sh"]
          args:
            - "-c"
            - "while true; do env; sleep 10; done"
