apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamster
  namespace: default
  labels:
    app.kubernetes.io/instance: myapp
spec:
  selector:
    matchLabels:
      app: hamster
  replicas: 2
  template:
    metadata:
      labels:
        app: hamster
    spec:
      containers:
        - name: hamster
          image: ubuntu
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
          command: ["/bin/sh"]
          args:
            - "-c"
            - "while true; do date; cat /etc/secret/*; sleep 10; done"
          volumeMounts:
          - name: secret-volume
            mountPath: "/etc/secret"
            readOnly: true
          - name: secret-volume-raw
            mountPath: "/etc/secret-raw"
            readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: example-secret
      - name: secret-volume-raw
        secret:
          secretName: raw-secret
