kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/secret-version: 2
    avp.kubernetes.io/path: secret/data/accounts/aws
stringData:
  MY_SECRET: <AWS_ACCESS_KEY_ID>
